[postgres]
url = "postgresql://postgres.bdyrcyqvceonajaxbfwx:Rezadwi456!@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"

[openrouter]
api_key = "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"
